server:
  port: 8080
  context-path: /api
spring:
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /jsp/
      # 响应页面默认后缀
      suffix: .jsp
  application:
    name: jky-cloud-mybatis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      primary:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/mysql?characterEncoding=utf8&useUnicode=true&sessionVariables=storage_engine%3DInnoDB&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        driverClassName: com.mysql.jdbc.Driver
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://122.114.216.173:3306/gdjt?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
        url: jdbc:mysql://172.10.2.12:3306/exportfactoring?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
        username: zhaobinxu
        password: zhaobinxu
#        username: mysql
#        password: Boss@508
        druid.web-stat-filter.enabled: false 
        initial-size: 5
        max-active: 800
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
      second:
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.1.133:1521:orcl
        username: rybtxj2016
        password: rybtxj2016
        initial-size: 5
        max-active: 5
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
  http:
    multipart:
      enabled:  true
      max-file-size: 100MB
      max-request-size: 100Mb
      file-size-threshold: 0
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: hxmwugnieovabhgg
    username: 372920173@qq.com
    properties:
      mail:
        smtp: true
        timeout: 25000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      # 连接池最大连接数(使用负值表示没有限制)
      max-active: 200
      # 连接池最大阻塞等待时间(使用负值表示没有限制)
      max-wait: -1
      # 连接池中最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间(毫秒)
    timeout: 1000

#    spring.datasource.test.driverClassName: com.mysql.jdbc.Driver
#    spring.datasource.test.url: jdbc:mysql://172.17.11.39:3306/jeecms_testgjds?useUnicode=true&characterEncoding=utf-8
#    spring.datasource.test.username: root
#    spring.datasource.test.password: Boss@508
#  custom:
#  second-datasource:
#  datasource:
#    names: ds1,ds2
#    ds1:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.17.11.39:3306/jeecms_testgjds
#    username: root
#    password: Boss@508
#    druid.web-stat-filter.enabled: false
#    ds2:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.17.11.39:3306/jeecms_testgjds
#    username: root
#    password: Boss@508
#    druid.web-stat-filter.enabled: false
    
mybatis:
  mapper-locations: classpath*:/mapping/**Mapper.xml
  #classpath:mapping/*.xml
  type-aliases-package: com.exportfactoring.model
logging:
    level:
      com.exportfactoring.lab.monitor: DEBUG
      server:
    port: 80
    servlet:
      context-path: /
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

    